<!-- BLOC D'INSTRUCTION POUR AJOUTER UN UTILISATEUR -->


<?php
//AJOUTE UNIQUEMENT DANS LA BDD C# PUISQU'IL SUFFIRA DE FAIRE L'IMPORTATION POUR CLONE SUR LA BDD WEB

?>

<!-- FIN BLOC D'INSTRUCTION POUR AJOUTER UN UTILISATEUR -->
